sudo: true

install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.42.2/hugo_0.42.2_Linux-64bit.deb
- sudo dpkg -i hugo_0.42.2_Linux-64bit.deb

script:
- hugo version
- hugo

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: public
  github-token: $GITHUB_TOKEN
  fqdn: www.dashdashzako.net
  on:
    branch: master
