baseURL = "https://dashdashzako.net/"
languageCode = "en"
title = "dashdashzako"
description = "Small fish in a big pond"
theme = "ddz"

pygmentsUseClasses = true
pygmentsCodeFences = true

[params]
  logo = "/img/minnow-square.jpg"

[permalinks]
  post = "/:year/:title/"

[author]
  name = "dashdashzako"
