baseURL = "https://dashdashzako.net/"
languageCode = "en-us"
title = "dashdashzako"
theme = "ddz"

pygmentsStyle = "monokai"
pygmentsCodeFences = true

[permalinks]
  post = "/:year/:title/"

[author]
  name = "dashdashzako"
