baseURL = "https://dashdashzako.net/"
languageCode = "en"
title = "dashdashzako"
theme = "ddz"

pygmentsUseClasses = true
pygmentsCodeFences = true

[params]
  logo = "/img/minnow-square.jpg"
  description = "Small fish in a big pond"

[permalinks]
  post = "/:year/:slug/"

[author]
  name = "dashdashzako"
