baseURL = "https://dashdashzako.net/"
languageCode = "en-us"
title = "dashdashzako"
description = ""
theme = "ddz"

enableGitInfo = true
pygmentsUseClasses = true
pygmentsCodeFences = true

[params]
  logo = "/img/minnow-square.jpg"

[permalinks]
  post = "/:year/:title/"

[author]
  name = "dashdashzako"
